# Generated by Django 2.2.6 on 2019-11-12 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aristotle_mdr', '0073_squashed_0075__v310_squishy_part2'),
    ]

    replaces = [
        ('aristotle_mdr_validators', '0001_initial'),
        ('aristotle_mdr_validators', '0002_auto_20190916_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryValidationRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RAValidationRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.TextField(default='')),
                ('registration_authority', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.RegistrationAuthority')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
