# Generated by Django 2.2.6 on 2019-11-11 02:32

import aristotle_mdr.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aristotle_mdr', '0018_improve_request_reviews'),
    ]
    replaces = [
        ('aristotle_mdr_links', '0001_initial'),
        ('aristotle_mdr_links', '0002_auto_20170208_1819'),
        ('aristotle_mdr_links', '0003_auto_20170328_1941'),
        ('aristotle_mdr_links', '0004_make_relation_arity_nullable'),
        ('aristotle_mdr_links', '0005_switch_to_concept_relations'),
        ('aristotle_mdr_links', '0006_link_root_item'),
        ('aristotle_mdr_links', '0007_migrate_root_item'),
        ('aristotle_mdr_links', '0008_root_non_nullable'),
        ('aristotle_mdr_links', '0009_remove_relation_arity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('_concept_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aristotle_mdr._concept')),
            ],
            options={
                'abstract': False,
            },
            bases=('aristotle_mdr._concept',),
        ),
        migrations.CreateModel(
            name='RelationRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='The primary name used for human identification purposes.')),
                ('definition', models.TextField(help_text='Representation of a concept by a descriptive statement which serves to differentiate it from related concepts. (3.2.39)', verbose_name='definition')),
                ('multiplicity', models.PositiveIntegerField(blank=True, help_text='number of links which must (logically) be members of the source relation of this role, differing only by an end with this role as an end_role.', null=True)),
                ('ordinal', models.PositiveIntegerField(help_text='order of the relation role among other relation roles in the relation.')),
                ('relation', aristotle_mdr.fields.ConceptForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr_links.Relation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('concept', aristotle_mdr.fields.ConceptForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr._concept')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr_links.Link')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr_links.RelationRole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='link',
            name='relation',
            field=aristotle_mdr.fields.ConceptForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr_links.Relation'),
        ),
        migrations.AddField(
            model_name='link',
            name='root_item',
            field=aristotle_mdr.fields.ConceptForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_links', to='aristotle_mdr._concept'),
        ),
    ]
