# Generated by Django 2.2.4 on 2019-09-18 06:11

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('aristotle_mdr_links', 'relationrole')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid1()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_links', '0010_relationrole_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
