# Generated by Django 2.2.5 on 2019-10-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0084_auto_20191015_1736'),
        ('aristotle_mdr_links', '0012_auto_20190918_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkend',
            name='role_temp',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
