# Generated by Django 2.2.5 on 2019-10-16 04:40

from django.db import migrations
from aristotle_mdr.utils.migration_utils import data_copy_and_paste_foreign_value


def duplicate_models_foreign_keys(apps, schema_editor):
    LinkEnd = apps.get_model('aristotle_mdr_links', 'linkend')
    data_copy_and_paste_foreign_value(LinkEnd, 'role', 'uuid', 'role_temp')


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_links', '0013_add_temp_field'),
    ]

    operations = [
        migrations.RunPython(duplicate_models_foreign_keys, reverse_code=migrations.RunPython.noop),
    ]
