# Generated by Django 2.2.5 on 2019-10-16 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_links', '0015_make_uuid_field_the_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkend',
            name='role',
            field=models.ForeignKey(blank=True,
                                    null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='RelationRole'),
        ),
    ]
