# Generated by Django 2.2.5 on 2019-10-16 05:58

from django.db import migrations
from aristotle_mdr.utils.migration_utils import data_copy_and_paste


def duplicate_model_foreign_keys(apps, schema_editor):
    LinkEnd = apps.get_model('aristotle_mdr_links', 'linkend')
    data_copy_and_paste(LinkEnd, 'role_temp', 'role_id')


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_links', '0016_add_foreign_key_field'),
    ]

    operations = [
        migrations.RunPython(duplicate_model_foreign_keys, reverse_code=migrations.RunPython.noop),
    ]
