# Generated by Django 2.2.5 on 2019-10-16 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_links', '0017_copy_and_paste_to_foreign_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkend',
            name='role_temp'
        )
    ]
