# Generated by Django 2.2.5 on 2019-10-24 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_links', '0019_auto_20191024_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkend',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr_links.RelationRole'),
        ),
    ]
