# Generated by Django 2.2.6 on 2019-11-11 02:09

import aristotle_mdr.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aristotle_mdr', '0075_auto_20190916_1602'),
    ]

    replaces = [
        ('aristotle_mdr_issues', '0001_initial'),
        ('aristotle_mdr_issues', '0002_issue_submitter'),
        ('aristotle_mdr_issues', '0003_auto_20181105_0545'),
        ('aristotle_mdr_issues', '0004_issuecomment'),
        ('aristotle_mdr_issues', '0005_auto_20190514_1534'),
        ('aristotle_mdr_issues', '0006_auto_20190517_1547'),
        ('aristotle_mdr_issues', '0007_auto_20190809_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('isopen', models.BooleanField(default=True)),
                ('proposal_field', models.TextField(blank=True, choices=[('name', 'Name'), ('definition', 'Definition'), ('references', 'References'), ('origin', 'Origin'), ('comments', 'Comments')])),
                ('proposal_value', models.TextField(blank=True)),
                ('item', aristotle_mdr.fields.ConceptForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='aristotle_mdr._concept')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('stewardship_organisation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.StewardOrganisation', to_field='uuid')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_comments', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='aristotle_mdr_issues.Issue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, to='aristotle_mdr_issues.IssueLabel'),
        ),
        migrations.AddField(
            model_name='issue',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
