# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 01:53
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_issues', '0004_issuecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='proposals',
            field=jsonfield.fields.JSONField(default='{}'),
        ),
    ]
