# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_issues', '0005_issue_proposals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='proposals',
        ),
        migrations.AddField(
            model_name='issue',
            name='proposal_field',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='proposal_value',
            field=models.TextField(blank=True),
        ),
    ]
