# Generated by Django 2.2.6 on 2019-11-11 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aristotle_mdr', '0075_auto_20190916_1602'),
    ]

    replaces = [
        ('aristotle_glossary', '0001_squashed_0003_fix_concept_fields'),
        ('aristotle_glossary', '0002_auto_20190809_1241'),
        ('aristotle_glossary', '0003_auto_20190916_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryItem',
            fields=[
                ('_concept_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aristotle_mdr._concept')),
                ('index', models.ManyToManyField(blank=True, related_name='related_glossary_items', to='aristotle_mdr._concept')),
            ],
            options={
                'abstract': False,
            },
            bases=('aristotle_mdr._concept',),
        ),
    ]
