# Generated by Django 2.2.6 on 2019-11-11 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('aristotle_mdr', '0075_auto_20190916_1602'),
    ]
    replaces = [
        ('aristotle_mdr_favourites', '0001_initial'),
        ('aristotle_mdr_favourites', '0002_auto_20180904_0422'),
        ('aristotle_mdr_favourites', '0003_auto_20180907_0105'),
        ('aristotle_mdr_favourites', '0004_auto_20180913_2021'),
        ('aristotle_mdr_favourites', '0005_auto_20190809_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('primary', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='aristotle_mdr.PossumProfile')),
            ],
            options={
                'unique_together': {('profile', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='aristotle_mdr._concept')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='aristotle_mdr_favourites.Tag')),
            ],
            options={
                'unique_together': {('tag', 'item')},
            },
        ),
    ]
