# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 05:44
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_backwards', '0002_auto_20190118_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationscheme',
            name='classificationStructure',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
