# Generated by Django 2.2.6 on 2019-11-11 02:07

import aristotle_mdr.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('aristotle_mdr', '0075_auto_20190916_1602'),
    ]
    replaces = [
        ('aristotle_mdr_identifiers', '0001_initial'),
        ('aristotle_mdr_identifiers', '0002_auto_20161124_1520'),
        ('aristotle_mdr_identifiers', '0003_switch_to_concept_relations'),
        ('aristotle_mdr_identifiers', '0004_scopedidentifier_order'),
        ('aristotle_mdr_identifiers', '0005_auto_20180624_2049'),
        ('aristotle_mdr_identifiers', '0006_auto_20190320_1304'),
        ('aristotle_mdr_identifiers', '0007_auto_20190502_1036'),
        ('aristotle_mdr_identifiers', '0008_auto_20190503_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid1, editable=False, help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries', unique=True)),
                ('name', aristotle_mdr.fields.ShortTextField(help_text='The primary name used for human identification purposes.')),
                ('definition', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='Representation of a concept by a descriptive statement which serves to differentiate it from related concepts. (3.2.39)', verbose_name='definition')),
                ('shorthand_prefix', models.CharField(help_text='prefix conventionally used as shorthand for a namespace, for greater readability, in text for human consumption.', max_length=512)),
                ('stewardship_organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.StewardOrganisation', to_field='uuid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScopedIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('identifier', models.CharField(help_text='String used to unambiguously denote an Item within the scope of a specified Namespace.', max_length=512)),
                ('version', models.CharField(blank=True, default='', help_text='unique version identifier of the Scoped_Identifier which identifies an Item', max_length=512)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('concept', aristotle_mdr.fields.ConceptForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='aristotle_mdr._concept')),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr_identifiers.Namespace')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('namespace', 'identifier', 'version')},
            },
        ),
    ]
