# Generated by Django 2.2.4 on 2019-09-18 06:11

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('aristotle_mdr_identifiers', 'scopedidentifier')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid1()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_identifiers', '0009_scopedidentifier_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
