# Generated by Django 2.2.4 on 2019-09-18 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mallard_qr', '0008_auto_20190809_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsedomain',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False, help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries', unique=True),
        ),
    ]
