# Generated by Django 2.2.4 on 2019-09-18 06:13

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('mallard_qr', 'responsedomain')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid1()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('mallard_qr', '0009_responsedomain_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
