# Generated by Django 2.2.6 on 2019-10-21 01:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mallard_qr', '0011_auto_20190918_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsedomain',
            name='id',
        ),
        migrations.AlterField(
            model_name='responsedomain',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False, help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries', primary_key=True, serialize=False, unique=True),
        ),
    ]
