# Generated by Django 2.2.6 on 2019-11-11 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mallard_qr', '0012_auto_20191021_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsedomain',
            old_name='uuid',
            new_name='id',
        ),
    ]
