# Generated by Django 2.2.6 on 2019-11-12 05:43

import aristotle_mdr.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aristotle_mdr', '0073_squashed_0075__v310_squishy_part2'),
        ('aristotle_dse', '0001_squashed_0030_initial_squishy'),
    ]

    replaces = [
        ('comet', '0001_initial'),
        ('comet', '0002_auto_20150730_1153'),
        ('comet', '0003_indicator_outcomearea'),
        ('comet', '0004_auto_20160227_1732'),
        ('comet', '0005_auto_20160227_2258'),
        ('comet', '0006_auto_20160314_1629'),
        ('comet', '0007_promote_framework_to_concept'),
        ('comet', '0008_fix_concept_fields'),
        ('comet', '0002_indicatorsettype_uuid'),
        ('comet', '0003_auto_20170714_1609'),

        ('comet', '0001_squashed_0008_fix_concept_fields'),
        ('comet', '0002_squashed_0003_auto_20170714_1609'),
        ('comet', '0003_auto_20171030_0154'),
        ('comet', '0004_auto_20180206_0327'),
        ('comet', '0005_auto_20181107_0433'),
        ('comet', '0006_auto_20190212_0935'),
        ('comet', '0007_auto_20190218_0246'),
        ('comet', '0008_auto_20190218_0404'),
        ('comet', '0009_auto_20190320_2035'),
        ('comet', '0010_auto_20190417_2001'),
        ('comet', '0011_auto_20190427_2149'),
        ('comet', '0012_auto_20190523_2157'),
        ('comet', '0013_auto_20190711_0117'),
        ('comet', '0014_auto_20190716_0859'),
        ('comet', '0016_auto_20190801_1119'),
        ('comet', '0017_auto_20190809_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('_concept_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aristotle_mdr._concept')),
            ],
            options={
                'abstract': False,
            },
            bases=('aristotle_mdr._concept',),
        ),
        migrations.CreateModel(
            name='FrameworkDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=2048)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('framework', aristotle_mdr.fields.ConceptForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comet.Framework')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_dimensions', to='comet.FrameworkDimension')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('_concept_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aristotle_mdr._concept')),
                ('computation_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('computation', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('numerator_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('denominator_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('disaggregation_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('rationale', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('benchmark', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('reporting_information', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('dimensions', aristotle_mdr.fields.ConceptManyToManyField(blank=True, related_name='indicators', to='comet.FrameworkDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('aristotle_mdr._concept',),
        ),
        migrations.CreateModel(
            name='IndicatorSet',
            fields=[
                ('_concept_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aristotle_mdr._concept')),
            ],
            options={
                'abstract': False,
            },
            bases=('aristotle_mdr._concept',),
        ),
        migrations.CreateModel(
            name='OutcomeArea',
            fields=[
                ('_concept_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aristotle_mdr._concept')),
            ],
            options={
                'abstract': False,
            },
            bases=('aristotle_mdr._concept',),
        ),
        migrations.CreateModel(
            name='QualityStatement',
            fields=[
                ('_concept_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aristotle_mdr._concept')),
                ('institutional_environment', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('timeliness', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('accessibility', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('interpretability', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('relevance', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('accuracy', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('coherence', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('aristotle_mdr._concept',),
        ),
        migrations.CreateModel(
            name='IndicatorNumeratorDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='The position of this data element in the indicator', verbose_name='Order')),
                ('guide_for_use', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('data_element', aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_mdr.DataElement')),
                ('data_set', aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_dse.Dataset')),
                ('data_set_specification', aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_dse.DataSetSpecification')),
                ('indicator', aristotle_mdr.fields.ConceptForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comet.Indicator')),
            ],
            options={
                'verbose_name': 'Numerator',
            },
        ),
        migrations.CreateModel(
            name='IndicatorInclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='The position of this indicator in the set', verbose_name='Order')),
                ('name', models.CharField(blank=True, help_text='The name identifying this indicator in the set', max_length=1024)),
                ('indicator', aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comet.Indicator')),
                ('indicator_set', aristotle_mdr.fields.ConceptForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comet.IndicatorSet')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorDisaggregationDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='The position of this data element in the indicator', verbose_name='Order')),
                ('guide_for_use', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('data_element', aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_mdr.DataElement')),
                ('data_set', aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_dse.Dataset')),
                ('data_set_specification', aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_dse.DataSetSpecification')),
                ('indicator', aristotle_mdr.fields.ConceptForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comet.Indicator')),
            ],
            options={
                'verbose_name': 'Disaggregator',
            },
        ),
        migrations.CreateModel(
            name='IndicatorDenominatorDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='The position of this data element in the indicator', verbose_name='Order')),
                ('guide_for_use', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('data_element', aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_mdr.DataElement')),
                ('data_set', aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_dse.Dataset')),
                ('data_set_specification', aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_dse.DataSetSpecification')),
                ('indicator', aristotle_mdr.fields.ConceptForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comet.Indicator')),
            ],
            options={
                'verbose_name': 'Denominator',
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='outcome_areas',
            field=aristotle_mdr.fields.ConceptManyToManyField(blank=True, related_name='indicators', to='comet.OutcomeArea'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='quality_statement',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, help_text='A statement of multiple quality dimensions for the purpose of assessing the quality of the data for reporting against this Indicator.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comet.QualityStatement'),
        ),
    ]
