# Generated by Django 2.2.4 on 2019-09-18 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0001_squashed_0018_initial_squishy'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameworkdimension',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid1,
                editable=False,
                help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='indicatordenominatordefinition',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid1,
                editable=False,
                help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='indicatordisaggregationdefinition',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid1,
                editable=False,
                help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='indicatorinclusion',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid1,
                editable=False,
                help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='indicatornumeratordefinition',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid1,
                editable=False,
                help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                null=True
            ),
        ),
    ]
