# Generated by Django 2.2.4 on 2019-09-18 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0017_auto_20190809_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameworkdimension',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False, help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries', unique=True),
        ),
        migrations.AddField(
            model_name='indicatordenominatordefinition',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False, help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries', unique=True),
        ),
        migrations.AddField(
            model_name='indicatordisaggregationdefinition',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False, help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries', unique=True),
        ),
        migrations.AddField(
            model_name='indicatorinclusion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False, help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries', unique=True),
        ),
        migrations.AddField(
            model_name='indicatornumeratordefinition',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False, help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries', unique=True),
        ),
        migrations.AlterField(
            model_name='frameworkdimension',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='frameworkdimension',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='frameworkdimension',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
