# Generated by Django 2.2.4 on 2019-09-18 06:12

from django.db import migrations
import uuid


def generate_uuids_for_frameworkdimension(apps, schema_editor):
    model = apps.get_model('comet', 'frameworkdimension')
    for row in model.objects.all():
        row.uuid = uuid.uuid1()
        row.save(update_fields=['uuid'])


def generate_uuids_for_indicatordenominatordefinition(apps, schema_editor):
    model = apps.get_model('comet', 'indicatordenominatordefinition')
    for row in model.objects.all():
        row.uuid = uuid.uuid1()
        row.save(update_fields=['uuid'])


def generate_uuids_for_indicatordisaggregationdefinition(apps, schema_editor):
    model = apps.get_model('comet', 'indicatordisaggregationdefinition')
    for row in model.objects.all():
        row.uuid = uuid.uuid1()
        row.save(update_fields=['uuid'])


def generate_uuids_for_indicatorinclusion(apps, schema_editor):
    model = apps.get_model('comet', 'indicatorinclusion')
    for row in model.objects.all():
        row.uuid = uuid.uuid1()
        row.save(update_fields=['uuid'])


def generate_uuids_for_indicatornumeratordefinition(apps, schema_editor):
    model = apps.get_model('comet', 'indicatornumeratordefinition')
    for row in model.objects.all():
        row.uuid = uuid.uuid1()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0018_auto_20190918_1526'),
    ]

    operations = [
        migrations.RunPython(generate_uuids_for_frameworkdimension, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(generate_uuids_for_indicatordenominatordefinition, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(generate_uuids_for_indicatordisaggregationdefinition, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(generate_uuids_for_indicatorinclusion, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(generate_uuids_for_indicatornumeratordefinition, reverse_code=migrations.RunPython.noop),
    ]
