# Generated by Django 2.2.4 on 2019-09-18 06:12

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):

    def generate_uuids_for_model(model):
        for row in model.objects.all():
            row.uuid = uuid.uuid1()
            row.save(update_fields=['uuid'])

    generate_uuids_for_model(apps.get_model('comet', 'frameworkdimension'))
    generate_uuids_for_model(apps.get_model('comet', 'indicatordenominatordefinition'))
    generate_uuids_for_model(apps.get_model('comet', 'indicatordisaggregationdefinition'))
    generate_uuids_for_model(apps.get_model('comet', 'indicatorinclusion'))
    generate_uuids_for_model(apps.get_model('comet', 'indicatornumeratordefinition'))


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0018_auto_20190918_1526'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
