# Generated by Django 2.2.5 on 2019-10-01 03:38

import aristotle_mdr.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0023_remove_rename_and_alter_parent_field'),
        ('aristotle_mdr', '0081_remove_rename_and_alter_abstractvalue_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorFrameworkDimensionsThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frameworkdimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comet.FrameworkDimension', to_field='uuid')),
                ('indicator', aristotle_mdr.fields.ConceptForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comet.Indicator')),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='dimensions_new',
            field=aristotle_mdr.fields.ConceptManyToManyField(blank=True, related_name='indicators_new', through='comet.IndicatorFrameworkDimensionsThrough', to='comet.FrameworkDimension'),
        ),
    ]
