# Generated by Django 2.2.5 on 2019-10-02 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0025_copy_and_paste_data_through'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='dimensions',
        ),
    ]
