# Generated by Django 2.2.5 on 2019-10-03 06:23

import aristotle_mdr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0026_remove_indicator_dimensions'),
        ('aristotle_mdr', '0081_remove_rename_and_alter_abstractvalue_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='dimensions_new',
            field=aristotle_mdr.fields.ConceptManyToManyField(blank=True, related_name='indicators', through='comet.IndicatorFrameworkDimensionsThrough', to='comet.FrameworkDimension'),
        ),
    ]
