# Generated by Django 2.2.5 on 2019-10-17 01:18

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0028_rename_dimensions_new_field_to_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatornumeratordefinition',
            name='id',
        ),
        migrations.RemoveField(
            model_name='indicatordenominatordefinition',
            name='id',
        ),
        migrations.RemoveField(
            model_name='indicatordisaggregationdefinition',
            name='id',
        ),
        migrations.RemoveField(
            model_name='indicatorinclusion',
            name='id',
        ),
        migrations.AlterField(
            model_name='indicatornumeratordefinition',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False,
                                   help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                                   primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='indicatordenominatordefinition',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False,
                                   help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                                   primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='indicatordisaggregationdefinition',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False,
                                   help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                                   primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='indicatorinclusion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False,
                                   help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                                   primary_key=True, serialize=False, unique=True),
        ),
    ]
