# Generated by Django 2.2.5 on 2019-10-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0029_change_pk_to_uuid_for_non_referenced_comet_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorframeworkdimensionsthrough',
            name='frameworkdimension_temp',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frameworkdimension',
            name='parent_temp',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
