# Generated by Django 2.2.5 on 2019-10-17 02:40
from django.db import migrations
from aristotle_mdr.utils.migration_utils import data_copy_and_paste_foreign_value


def duplicate_models_foreign_keys(apps, schema_editor):
    IndicatorFrameworkDimensionsThrough = apps.get_model('comet', 'indicatorframeworkdimensionsthrough')
    FrameworkDimension = apps.get_model('comet', 'frameworkdimension')
    data_copy_and_paste_foreign_value(IndicatorFrameworkDimensionsThrough, 'frameworkdimension', 'uuid', 'frameworkdimension_temp')
    data_copy_and_paste_foreign_value(FrameworkDimension, 'parent', 'uuid', 'parent_temp')


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0030_add_temp_field'),
    ]

    operations = [
        migrations.RunPython(duplicate_models_foreign_keys, reverse_code=migrations.RunPython.noop),
    ]
