# Generated by Django 2.2.5 on 2019-10-17 03:42
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0031_copy_and_paste_foreign_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frameworkdimension',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='indicatorframeworkdimensionsthrough',
            name='frameworkdimension',
        ),
        migrations.RemoveField(
            model_name='frameworkdimension',
            name='id',
        ),
        migrations.AlterField(
            model_name='frameworkdimension',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False,
                                   help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                                   primary_key=True, serialize=False, unique=True),
        ),
    ]
