# Generated by Django 2.2.5 on 2019-10-17 03:53
import mptt.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0032_make_uuid_field_the_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameworkdimension',
            name='parent',
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                to='comet.FrameworkDimension',
                related_name='child_dimensions',
                on_delete=django.db.models.deletion.CASCADE),
        ),
        migrations.AddField(
            model_name='indicatorframeworkdimensionsthrough',
            name='frameworkdimension',
            field=models.ForeignKey(
                blank=True,
                null=True,
                to='comet.FrameworkDimension',
                on_delete=django.db.models.deletion.CASCADE),
        ),
    ]
