# Generated by Django 2.2.5 on 2019-10-17 04:00

from django.db import migrations
from aristotle_mdr.utils.migration_utils import data_copy_and_paste


def duplicate_models_foreign_keys(apps, schema_editor):
    FrameworkDimension = apps.get_model('comet', 'frameworkdimension')
    IndicatorFrameworkDimensionsThrough = apps.get_model('comet', 'indicatorframeworkdimensionsthrough')
    data_copy_and_paste(FrameworkDimension, 'parent_temp', 'parent_id')
    data_copy_and_paste(IndicatorFrameworkDimensionsThrough, 'frameworkdimension_temp', 'frameworkdimension_id')


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0033_add_foreign_key_field'),
    ]

    operations = [
        migrations.RunPython(duplicate_models_foreign_keys, reverse_code=migrations.RunPython.noop),
    ]
