# Generated by Django 2.2.5 on 2019-10-17 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0034_copy_and_paste_to_foreign_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frameworkdimension',
            name='parent_temp',
        ),
        migrations.RemoveField(
            model_name='indicatorframeworkdimensionsthrough',
            name='frameworkdimension_temp',
        ),
    ]
