# Generated by Django 2.2.5 on 2019-10-24 06:00

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0035_remove_temp_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frameworkdimension',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='indicatordenominatordefinition',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='indicatordisaggregationdefinition',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='indicatorinclusion',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='indicatornumeratordefinition',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='frameworkdimension',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_dimensions', to='comet.FrameworkDimension', to_field='id'),
        ),
        migrations.AlterField(
            model_name='indicatorframeworkdimensionsthrough',
            name='frameworkdimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comet.FrameworkDimension', to_field='id'),
        ),
    ]
