# Generated by Django 2.2.5 on 2019-10-24 06:07

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0036_auto_20191024_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworkdimension',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_dimensions', to='comet.FrameworkDimension'),
        ),
        migrations.AlterField(
            model_name='indicatorframeworkdimensionsthrough',
            name='frameworkdimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comet.FrameworkDimension'),
        ),
    ]
