# Generated by Django 2.2.7 on 2020-01-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0037_set_null_to_false_in_through_table_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicatorframeworkdimensionsthrough',
            unique_together={('indicator', 'frameworkdimension')},
        ),
    ]
