# Generated by Django 2.2.6 on 2019-11-11 01:33

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    replaces = [
        ('aristotle_mdr_help', '0001_initial'),
        ('aristotle_mdr_help', '0002_helpbase_is_public'),
        ('aristotle_mdr_help', '0003_auto_20161124_1520'),
        ('aristotle_mdr_help', '0004_auto_20170530_2104'),
        ('aristotle_mdr_help', '0005_auto_20190731_1556'),
        ('aristotle_mdr_help', '0006_auto_20190814_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('app_label', models.CharField(blank=True, help_text='Add an app for app specific help, required for concept help', max_length=256, null=True)),
                ('title', models.TextField(help_text='A short title for the help page')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='A long help definition for an object or topic', null=True)),
                ('language', models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=7)),
                ('is_public', models.BooleanField(default=True, help_text='Indicates if a help topic is available to non-registered users.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptHelp',
            fields=[
                ('helpbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aristotle_mdr_help.HelpBase')),
                ('concept_type', models.CharField(max_length=256)),
                ('brief', models.TextField(help_text='A short description of the concept')),
                ('official_definition', models.TextField(blank=True, help_text='An official description of the concept, e.g. the ISO/IEC definition for an Object Class', null=True)),
                ('official_reference', models.TextField(blank=True, help_text='The reference document that describes this concept type', null=True)),
                ('official_link', models.TextField(blank=True, help_text='An link to an official source for a description of the concept', null=True)),
                ('creation_tip', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Instructions for creating good content of this type', null=True)),
            ],
            options={
                'ordering': ('concept_type', 'app_label'),
            },
            bases=('aristotle_mdr_help.helpbase',),
        ),
        migrations.CreateModel(
            name='HelpPage',
            fields=[
                ('helpbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aristotle_mdr_help.HelpBase')),
            ],
            options={
                'ordering': ('title',),
            },
            bases=('aristotle_mdr_help.helpbase',),
        ),
    ]
