# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-14 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0031_auto_20180629_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationauthority',
            name='active',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=True, help_text='<div id="active-alert" class="alert alert-warning" role="alert">Setting this to False will disable all further registration actions</div>'),
        ),
    ]
