# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 03:08
from __future__ import unicode_literals

from django.db import migrations, models

def move_to_new(apps, schema_migration):
    ra = apps.get_model('aristotle_mdr', 'RegistrationAuthority')

    for obj in ra.objects.all():
        if obj.active:
            obj.new_active = 0
        else:
            obj.new_active = 1

        obj.save()

def move_to_old(apps, schema_migration):
    ra = apps.get_model('aristotle_mdr', 'RegistrationAuthority')

    for obj in ra.objects.all():
        if obj.new_active == 0:
            obj.active = True
        else:
            obj.active = False

        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0031_auto_20180629_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationauthority',
            name='new_active',
            field=models.IntegerField(choices=[(0, 'Active & Visible'), (1, 'Inactive & Visible'), (2, 'Inactive & Hidden')], default=0, help_text='<div id="active-alert" class="alert alert-warning" role="alert">Setting this to Inactive will disable all further registration actions</div>'),
        ),
        migrations.RunPython(move_to_new, move_to_old),
    ]
