# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 05:12
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0037_make_name_shorttext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='_concept',
            name='submitting_organisation',
            field=aristotle_mdr.fields.ShortTextField(blank=True),
        ),
    ]
