# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0039_auto_20180828_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possumprofile',
            name='favourites',
        ),
    ]
