# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 22:27
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_backwards', '0001_squashed_0003_auto_20190118_0544'),
        ('aristotle_mdr', '0046_auto_20181107_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='possumprofile',
            name='notificationPermissions',
            field=jsonfield.fields.JSONField(default='{"metadata changes": {"general changes": {"items in my workgroups": true, "items I have tagged / favourited": true, "any items I can edit": true}, "superseded": {"items in my workgroups": true, "items I have tagged / favourited": true, "any items I can edit": true}, "new items": {"new items in my workgroups": true}}, "registrar": {"item superseded": true, "item registered": true, "item changed status": true, "review request created": true, "review request updated": true}, "issues": {"items in my workgroups": true, "items I have tagged / favourited": true, "any items I can edit": true}, "discussions": {"new posts": true, "new comments": true}, "notification methods": {"email": false, "within aristotle": true}}'),
        ),
        migrations.AddField(
            model_name='valuedomain',
            name='classification_scheme',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valueDomains', to='aristotle_mdr_backwards.ClassificationScheme', verbose_name='Classification Scheme'),
        ),
        migrations.AlterField(
            model_name='permissiblevalue',
            name='meaning',
            field=aristotle_mdr.fields.ShortTextField(blank=True, help_text="A textual designation of a value, where a relation to a Value meaning doesn't exist"),
        ),
        migrations.AlterField(
            model_name='supplementaryvalue',
            name='meaning',
            field=aristotle_mdr.fields.ShortTextField(blank=True, help_text="A textual designation of a value, where a relation to a Value meaning doesn't exist"),
        ),
    ]
