# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 05:00
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0046_auto_20181107_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='possumprofile',
            name='notificationPermissions',
            field=jsonfield.fields.JSONField(default={'discussions': {'new comments': True, 'new posts': True}, 'issues': {'any items I can edit': True, 'items I have tagged / favourited': True, 'items in my workgroups': True}, 'metadata changes': {'general changes': {'any items I can edit': True, 'items I have tagged / favourited': True, 'items in my workgroups': True}, 'new items': {'new items in my workgroups': True}, 'superseded': {'any items I can edit': True, 'items I have tagged / favourited': True, 'items in my workgroups': True}}, 'notification methods': {'email': False, 'within aristotle': True}, 'registrar': {'item changed status': True, 'item registered': True, 'item superseded': True, 'review request created': True, 'review request updated': True}}),
        ),
    ]
