# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-12 02:07
from __future__ import unicode_literals

import autoslug.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid

from aristotle_mdr.utils.migrations import (
    classproperty,
    StewardMigration
)


class Migration(StewardMigration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aristotle_mdr', '0046_auto_20181107_0433'),
    ]

    @classproperty
    def operations(cls):
        return [
            migrations.CreateModel(
                name='StewardOrganisation',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='name')),
                    ('name', models.TextField(help_text='The primary name used for human identification purposes.')),
                    ('uuid', models.UUIDField(default=uuid.uuid1, editable=False, unique=True)),
                    ('description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Representation of a concept by a descriptive statement which serves to differentiate it from related concepts. (3.2.39)', verbose_name='definition')),
                ],
                options={
                    'verbose_name': 'Steward Organisation',
                },
            ),
            migrations.CreateModel(
                name='StewardOrganisationMembership',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('role', models.CharField(choices=[('admin', 'Admin'), ('steward', 'Steward'), ('member', 'Member')], help_text='Role within this group', max_length=128)),
                    ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='aristotle_mdr.StewardOrganisation', to_field='uuid')),
                    ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ],
                options={
                    'abstract': False,
                },
            ),

            migrations.RunPython(cls.add_stewardship_org, migrations.RunPython.noop),
            migrations.RunPython(cls.fetch_stewardship_org_uuid, migrations.RunPython.noop),

            migrations.AddField(
                model_name='_concept',
                name='stewardship_organisation',
                field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.StewardOrganisation', to_field='uuid'),
                preserve_default=False,
            ),
            migrations.RunPython(cls.assign_orgs_to_metadata, migrations.RunPython.noop),

            migrations.AddField(
                model_name='organization',
                name='stewardship_organisation',
                field=models.ForeignKey(default=cls.get_uuid, on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.StewardOrganisation', to_field='uuid'),
                preserve_default=False,
            ),
            migrations.AddField(
                model_name='workgroup',
                name='stewardship_organisation',
                field=models.ForeignKey(default=cls.get_uuid, on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.StewardOrganisation', to_field='uuid'),
                preserve_default=False,
            ),
            migrations.AlterUniqueTogether(
                name='stewardorganisationmembership',
                unique_together=set([('user', 'group')]),
            ),
        ]
