# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 06:00
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_backwards', '0001_squashed_0003_auto_20190118_0544'),
        ('aristotle_mdr', '0046_auto_20181107_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='possumprofile',
            name='notificationPermissions',
            field=jsonfield.fields.JSONField(default={'discussions': {'new comments': True, 'new posts': True}, 'issues': {'any items I can edit': True, 'items I have tagged / favourited': True, 'items in my workgroups': True}, 'metadata changes': {'general changes': {'any items I can edit': True, 'items I have tagged / favourited': True, 'items in my workgroups': True}, 'new items': {'new items in my workgroups': True}, 'superseded': {'any items I can edit': True, 'items I have tagged / favourited': True, 'items in my workgroups': True}}, 'notification methods': {'email': False, 'within aristotle': True}, 'registrar': {'item changed status': True, 'item registered': True, 'item superseded': True, 'review request created': True, 'review request updated': True}}),
        ),
        migrations.AddField(
            model_name='valuedomain',
            name='classification_scheme',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valueDomains', to='aristotle_mdr_backwards.ClassificationScheme', verbose_name='Classification Scheme'),
        ),
        migrations.AlterField(
            model_name='permissiblevalue',
            name='meaning',
            field=aristotle_mdr.fields.ShortTextField(blank=True, help_text="A textual designation of a value, where a relation to a Value meaning doesn't exist"),
        ),
        migrations.AlterField(
            model_name='supplementaryvalue',
            name='meaning',
            field=aristotle_mdr.fields.ShortTextField(blank=True, help_text="A textual designation of a value, where a relation to a Value meaning doesn't exist"),
        ),
    ]
