# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-23 17:34
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion

from aristotle_mdr.utils.migrations import (
    classproperty,
    StewardMigration
)


class Migration(StewardMigration):

    dependencies = [
        ('aristotle_mdr', '0047_auto_20181217_0926'),
    ]

    @classproperty
    def operations(cls):
        return [
            migrations.RunPython(cls.fetch_stewardship_org_uuid, migrations.RunPython.noop),
            migrations.AddField(
                model_name='measure',
                name='stewardship_organisation',
                field=models.ForeignKey(default=cls.get_uuid, null=False, on_delete=django.db.models.deletion.CASCADE, related_name='managed_items', to='aristotle_mdr.StewardOrganisation', to_field='uuid'),
                preserve_default=False,
            ),
            migrations.AddField(
                model_name='measure',
                name='workgroup',
                field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_items', to='aristotle_mdr.Workgroup'),
            ),
            migrations.AddField(
                model_name='stewardorganisation',
                name='state',
                field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('hidden', 'Hidden')], default='active', help_text='Status of this group', max_length=128),
            ),
            migrations.AlterField(
                model_name='_concept',
                name='stewardship_organisation',
                field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='aristotle_mdr.StewardOrganisation', to_field='uuid'),
            ),
            migrations.AlterField(
                model_name='stewardorganisation',
                name='slug',
                field=autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True),
            ),
        ]
