# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-25 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0048_auto_20181223_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='workgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_items', to='aristotle_mdr.Workgroup'),
        ),
    ]
