# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 08:47
from __future__ import unicode_literals

from django.db import migrations



def move_to_new(apps, schema_migration):
    Workgroup = apps.get_model('aristotle_mdr', 'Workgroup')

    wgs = Workgroup.objects.all() #.prefetch_related('statuses')
    for wg in wgs:
        print("====================")
        print(wg.viewers.all())
        print(wg.managers.all())
        print("====================")


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0054_auto_20190313_1944'),
    ]

    operations = [
        migrations.RunPython(move_to_new, migrations.RunPython.noop),
    ]
