# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 06:42
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0065_orgainizationrecord_recordrelation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrgainizationRecord',
            new_name='OrganizationRecord',
        ),
        migrations.AlterField(
            model_name='recordrelation',
            name='concept',
            field=aristotle_mdr.fields.ConceptForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_records', to='aristotle_mdr._concept'),
        ),
    ]
