# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-25 11:19
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0067_auto_20190605_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiblevalue',
            name='value',
            field=aristotle_mdr.fields.ShortTextField(blank=True, help_text='the actual value of the Value'),
        ),
        migrations.AlterField(
            model_name='supplementaryvalue',
            name='value',
            field=aristotle_mdr.fields.ShortTextField(blank=True, help_text='the actual value of the Value'),
        ),
        migrations.AlterField(
            model_name='valuemeaning',
            name='name',
            field=models.CharField(blank=True, help_text='The semantic content of a possible value (3.2.141)', max_length=255),
        ),
    ]
