# Generated by Django 2.2.6 on 2019-11-11 04:13

import aristotle_mdr.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_backwards', '0004_auto_20190503_1505'),
        ('aristotle_mdr_review_requests', '0005_auto_20190809_1233'),
        ('aristotle_mdr', '0001_squashed_0072__v310_squishy_part1'),
    ]

    replaces = [
        ('aristotle_mdr', '0073_auto_20190814_1520'),
        ('aristotle_mdr', '0074_auto_20190908_0648'),
        ('aristotle_mdr', '0075_auto_20190916_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='supersederelationship',
            name='review',
            field=aristotle_mdr.fields.ConceptForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='aristotle_mdr_review_requests.ReviewRequest'),
        ),
        migrations.AddField(
            model_name='valuedomain',
            name='classification_scheme',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valueDomains', to='aristotle_mdr_backwards.ClassificationScheme', verbose_name='Classification Scheme'),
        ),
        migrations.AddField(
            model_name='valuedomain',
            name='representation_class',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='value_domains', to='aristotle_mdr_backwards.RepresentationClass', verbose_name='Representation Class'),
        ),
    ]
