# Generated by Django 2.2.4 on 2019-09-18 06:10

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):

    def generate_uuids_for_model(model):
        for row in model.objects.all():
            row.uuid = uuid.uuid1()
            row.save(update_fields=['uuid'])

    generate_uuids_for_model(apps.get_model('aristotle_mdr', 'dedderivesthrough'))
    generate_uuids_for_model(apps.get_model('aristotle_mdr', 'dedinputsthrough'))
    generate_uuids_for_model(apps.get_model('aristotle_mdr', 'permissiblevalue'))
    generate_uuids_for_model(apps.get_model('aristotle_mdr', 'supplementaryvalue'))
    generate_uuids_for_model(apps.get_model('aristotle_mdr', 'valuemeaning'))


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0076_auto_20190918_1524'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
