# Generated by Django 2.2.4 on 2019-09-18 06:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0077_generate_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dedderivesthrough',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid1,
                editable=False,
                help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                unique=True
            ),
        ),
        migrations.AlterField(
            model_name='dedinputsthrough',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid1,
                editable=False,
                help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                unique=True
            ),
        ),
        migrations.AlterField(
            model_name='permissiblevalue',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid1,
                editable=False,
                help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                unique=True
            ),
        ),
        migrations.AlterField(
            model_name='supplementaryvalue',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid1,
                editable=False,
                help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                unique=True
            ),
        ),
        migrations.AlterField(
            model_name='valuemeaning',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid1,
                editable=False,
                help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                unique=True
            ),
        ),
    ]
