# Generated by Django 2.2.5 on 2019-09-27 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0078_auto_20190918_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiblevalue',
            name='value_meaning_new',
            field=models.ForeignKey(blank=True, help_text='A reference to the value meaning that this designation relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissiblevalue_new_set', to='aristotle_mdr.ValueMeaning', to_field='uuid'),
        ),
        migrations.AddField(
            model_name='supplementaryvalue',
            name='value_meaning_new',
            field=models.ForeignKey(blank=True, help_text='A reference to the value meaning that this designation relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplementaryvalue_new_set', to='aristotle_mdr.ValueMeaning', to_field='uuid'),
        ),
    ]
