# Generated by Django 2.2.5 on 2019-09-30 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0079_auto_20190927_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiblevalue',
            name='value_meaning',
        ),
        migrations.RemoveField(
            model_name='supplementaryvalue',
            name='value_meaning',
        ),
    ]
