# Generated by Django 2.2.5 on 2019-09-27 06:05

from django.db import migrations
from aristotle_mdr.utils.migration_utils import data_copy_and_paste


def duplicate_models_foreign_keys(apps, schema_editor):
    permissible_value_model = apps.get_model('aristotle_mdr', 'permissiblevalue')
    supplementary_value_model = apps.get_model('aristotle_mdr', 'supplementaryvalue')
    data_copy_and_paste(permissible_value_model, 'value_meaning', 'value_meaning_new')
    data_copy_and_paste(supplementary_value_model, 'value_meaning', 'value_meaning_new')


def duplicate_models_foreign_keys_reverse(apps, schema_editor):
    permissible_value_model = apps.get_model('aristotle_mdr', 'permissiblevalue')
    supplementary_value_model = apps.get_model('aristotle_mdr', 'supplementaryvalue')
    data_copy_and_paste(permissible_value_model, 'value_meaning_new', 'value_meaning')
    data_copy_and_paste(supplementary_value_model, 'value_meaning_new', 'value_meaning')


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0079_auto_20190927_0105'),
    ]

    operations = [
        migrations.RunPython(duplicate_models_foreign_keys, reverse_code=duplicate_models_foreign_keys_reverse),
    ]
