# Generated by Django 2.2.6 on 2019-10-14 01:03

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0080_copy_and_paste_foreign_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiblevalue',
            name='value_meaning',
        ),
        migrations.RemoveField(
            model_name='supplementaryvalue',
            name='value_meaning',
        ),
        migrations.RemoveField(
            model_name='dedderivesthrough',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dedinputsthrough',
            name='id',
        ),
        migrations.RemoveField(
            model_name='permissiblevalue',
            name='id',
        ),
        migrations.RemoveField(
            model_name='supplementaryvalue',
            name='id',
        ),
        migrations.RemoveField(
            model_name='valuemeaning',
            name='id',
        ),
        migrations.AlterField(
            model_name='dedderivesthrough',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False,
                                   help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                                   primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='dedinputsthrough',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False,
                                   help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                                   primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='permissiblevalue',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False,
                                   help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                                   primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='supplementaryvalue',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False,
                                   help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                                   primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='valuemeaning',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False,
                                   help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries',
                                   primary_key=True, serialize=False, unique=True),
        ),
        migrations.RenameField(
            model_name='permissiblevalue',
            old_name='value_meaning_new',
            new_name='value_meaning',
        ),
        migrations.RenameField(
            model_name='supplementaryvalue',
            old_name='value_meaning_new',
            new_name='value_meaning',
        ),
        # Make the field a Foreign Key, and also remove the `related_name` attribute.
        migrations.AlterField(
            model_name='permissiblevalue',
            name='value_meaning',
            field=models.ForeignKey(blank=True,
                                    help_text='A reference to the value meaning that this designation relates to',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='aristotle_mdr.ValueMeaning'),
        ),
        migrations.AlterField(
            model_name='supplementaryvalue',
            name='value_meaning',
            field=models.ForeignKey(blank=True,
                                    help_text='A reference to the value meaning that this designation relates to',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='aristotle_mdr.ValueMeaning'),
        ),
    ]
