# Generated by Django 2.2.5 on 2019-09-30 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0080_copy_and_paste_abstract_values_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiblevalue',
            name='value_meaning',
        ),
        migrations.RemoveField(
            model_name='supplementaryvalue',
            name='value_meaning',
        ),
        migrations.RenameField(
            model_name='permissiblevalue',
            old_name='value_meaning_new',
            new_name='value_meaning',
        ),
        migrations.RenameField(
            model_name='supplementaryvalue',
            old_name='value_meaning_new',
            new_name='value_meaning',
        ),
        migrations.AlterField(
            model_name='permissiblevalue',
            name='value_meaning',
            field=models.ForeignKey(blank=True,
                                    help_text='A reference to the value meaning that this designation relates to',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='aristotle_mdr.ValueMeaning', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='supplementaryvalue',
            name='value_meaning',
            field=models.ForeignKey(blank=True,
                                    help_text='A reference to the value meaning that this designation relates to',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='aristotle_mdr.ValueMeaning', to_field='uuid'),
        ),
    ]
