# Generated by Django 2.2.5 on 2019-09-30 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0081_auto_20190929_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissiblevalue',
            old_name='value_meaning_new',
            new_name='value_meaning',
        ),
        migrations.RenameField(
            model_name='supplementaryvalue',
            old_name='value_meaning_new',
            new_name='value_meaning',
        ),
    ]
