# Generated by Django 2.2.5 on 2019-10-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0083_copy_and_paste_to_foreign_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiblevalue',
            name='value_meaning_new',
        ),
        migrations.RemoveField(
            model_name='supplementaryvalue',
            name='value_meaning_new',
        ),
    ]
