# Generated by Django 2.2.6 on 2019-11-11 01:19

import aristotle_mdr.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aristotle_mdr', '0075_auto_20190916_1602'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]
    replaces = [
        ('aristotle_mdr_custom_fields', '0001_squashed_0005_auto_20181206_0559'),
        ('aristotle_mdr_custom_fields', '0002_auto_20190212_1805'),
        ('aristotle_mdr_custom_fields', '0003_auto_20190408_1059'),
        ('aristotle_mdr_custom_fields', '0004_customfield_state'),
        ('aristotle_mdr_custom_fields', '0005_auto_20190519_2214'),
        ('aristotle_mdr_custom_fields', '0006_auto_20190606_2338'),
        ('aristotle_mdr_custom_fields', '0007_customfield_help_text_long'),
        ('aristotle_mdr_custom_fields', '0008_auto_20190711_0117'),
        ('aristotle_mdr_custom_fields', '0009_auto_20190809_1233'),
        ('aristotle_mdr_custom_fields', '0010_customfield_system_name'),
        ('aristotle_mdr_custom_fields', '0011_customfield_generate_system_name'),
        ('aristotle_mdr_custom_fields', '0012_customfield_system_name_uniqueness'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('int', 'Integer'), ('str', 'Text'), ('html', 'Rich Text'), ('date', 'Date'), ('enum', 'Choice')], max_length=10)),
                ('system_name', models.CharField(default='', help_text='A name used for uniquely identifying the custom field', max_length=1000, unique=True)),
                ('help_text', models.CharField(blank=True, max_length=1000)),
                ('help_text_long', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Longer contextual help and business rules describing a field.')),
                ('visibility', models.IntegerField(choices=[(0, 'Public'), (1, 'Authenticated'), (2, 'Workgroup'), (10, 'Registry Administrators')], default=0)),
                ('state', models.IntegerField(choices=[(0, 'Active & Visible'), (1, 'Inactive & Visible'), (2, 'Inactive & Hidden')], default=0)),
                ('choices', models.CharField(blank=True, max_length=1000)),
                ('allowed_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CustomValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content', models.TextField(blank=True)),
                ('concept', aristotle_mdr.fields.ConceptForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr._concept')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='aristotle_mdr_custom_fields.CustomField')),
            ],
            options={
                'ordering': ['field__order'],
                'unique_together': {('field', 'concept')},
            },
        ),
    ]
