# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0046_auto_20181107_0433'),
        ('aristotle_mdr_custom_fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='order',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customfield',
            name='help_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='type',
            field=models.CharField(choices=[('int', 'Integer'), ('str', 'Text'), ('html', 'Rich Text'), ('date', 'Date')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='customvalue',
            unique_together=set([('field', 'concept')]),
        ),
    ]
