# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 03:14
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0046_auto_20181107_0433'),
        ('aristotle_mdr_custom_fields', '0002_auto_20181129_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='allowed_models',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr._concept'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Authenticated'), (2, 'Workgroup')], default=0),
        ),
    ]
