# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_custom_fields', '0003_auto_20190408_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('custom_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aristotle_mdr_custom_fields.CustomField')),
                ('status', models.IntegerField(choices=[(0, 'Active & Visible'), (1, 'Inactive & Visible'), (2, 'Inactive & Hidden')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
