# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_custom_fields', '0003_auto_20181205_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='allowed_models',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
