# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_custom_fields', '0004_auto_20181205_0329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='customvalue',
            options={'ordering': ['field__order']},
        ),
        migrations.RenameField(
            model_name='customfield',
            old_name='allowed_models',
            new_name='allowed_model',
        ),
        migrations.AlterField(
            model_name='customvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='aristotle_mdr_custom_fields.CustomField'),
        ),
    ]
