# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_custom_fields', '0005_customfield_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='custom_field',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
