# Generated by Django 2.2.5 on 2019-09-11 23:45

from django.db import migrations

def generate_system_name(apps, schema_editor):
    CustomField = apps.get_model('aristotle_mdr_custom_fields', 'CustomField')
    for custom_field in CustomField.objects.all():
        if not custom_field.system_name:
            custom_field.system_name =


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_custom_fields', '0010_customfield_system_name'),
    ]

    operations = [
        migrations.RunPython(generate_system_name, reverse_code=migrations.RunPython.noop),
    ]
