name: Check for unapplied Django migrations
on: [pull_request]

jobs:
  build:
    name: Check for unapplied Django migrations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v1  # Equivalent to running git fetch and git checkout

      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install Pip & Pipenv
        run: pip install -U setuptools pip pipenv

      - name: Install postgres dependencies (required for install of Pipfile dependencies)
        run: sudo apt-get update && sudo apt-get install libpq-dev

      - name: Install Pip dependencies
        run: pipenv install --deploy --dev --system

      - name: Check for unapplied migrations
        env:
          DJANGO_SETTINGS_MODULE: "aristotle_mdr.required_settings"
          DATABASE_URL: "sqlite://:memory:"
        run: "django-admin makemigrations --check"

